"""empty message

Revision ID: 8f5b81933683
Revises: 4187b5ab9660
Create Date: 2018-12-23 18:20:21.491099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5b81933683'
down_revision = '4187b5ab9660'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('address', sa.String(length=200), nullable=False))
    op.add_column('address', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'address', ['user_id'])
    op.drop_constraint(u'address_users_id_fkey', 'address', type_='foreignkey')
    op.create_foreign_key(None, 'address', 'users', ['user_id'], ['id'])
    op.drop_column('address', 'users_id')
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.add_column('address', sa.Column('users_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.create_foreign_key(u'address_users_id_fkey', 'address', 'users', ['users_id'], ['id'])
    op.drop_constraint(None, 'address', type_='unique')
    op.drop_column('address', 'user_id')
    op.drop_column('address', 'address')
    # ### end Alembic commands ###
